/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedFamiliaRouteImport } from './routes/_authenticated/familia'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedManutencaoRouteImport } from './routes/_authenticated/manutencao'
import { Route as AuthenticatedMemoriasRouteImport } from './routes/_authenticated/memorias'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamiliaRoute = AuthenticatedFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencaoRoute = AuthenticatedManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoriasRoute = AuthenticatedMemoriasRouteImport.update({
  id: '/memorias',
  path: '/memorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ia': typeof AuthenticatedIaRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/memorias': typeof AuthenticatedMemoriasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ia': typeof AuthenticatedIaRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/memorias': typeof AuthenticatedMemoriasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/familia': typeof AuthenticatedFamiliaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/manutencao': typeof AuthenticatedManutencaoRoute
  '/_authenticated/memorias': typeof AuthenticatedMemoriasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ajuda'
    | '/calendario'
    | '/categorias'
    | '/compras'
    | '/configuracoes'
    | '/familia'
    | '/financeiro'
    | '/ia'
    | '/manutencao'
    | '/memorias'
    | '/onboarding'
    | '/perfil'
    | '/tarefas'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ajuda'
    | '/calendario'
    | '/categorias'
    | '/compras'
    | '/configuracoes'
    | '/familia'
    | '/financeiro'
    | '/ia'
    | '/manutencao'
    | '/memorias'
    | '/onboarding'
    | '/perfil'
    | '/tarefas'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ajuda'
    | '/_authenticated/calendario'
    | '/_authenticated/categorias'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/familia'
    | '/_authenticated/financeiro'
    | '/_authenticated/ia'
    | '/_authenticated/manutencao'
    | '/_authenticated/memorias'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/tarefas'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familia': {
      id: '/_authenticated/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof AuthenticatedFamiliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencao': {
      id: '/_authenticated/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memorias': {
      id: '/_authenticated/memorias'
      path: '/memorias'
      fullPath: '/memorias'
      preLoaderRoute: typeof AuthenticatedMemoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFamiliaRoute: typeof AuthenticatedFamiliaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedManutencaoRoute: typeof AuthenticatedManutencaoRoute
  AuthenticatedMemoriasRoute: typeof AuthenticatedMemoriasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFamiliaRoute: AuthenticatedFamiliaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedManutencaoRoute: AuthenticatedManutencaoRoute,
  AuthenticatedMemoriasRoute: AuthenticatedMemoriasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
