GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.homes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.home_members TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tasks TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.task_history TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.shopping_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.maintenance_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.expenses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.incomes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.memories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.achievements TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_insights TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_messages TO authenticated;

GRANT ALL ON public.profiles TO service_role;
GRANT ALL ON public.homes TO service_role;
GRANT ALL ON public.home_members TO service_role;
GRANT ALL ON public.tasks TO service_role;
GRANT ALL ON public.task_history TO service_role;
GRANT ALL ON public.shopping_items TO service_role;
GRANT ALL ON public.inventory_items TO service_role;
GRANT ALL ON public.maintenance_items TO service_role;
GRANT ALL ON public.events TO service_role;
GRANT ALL ON public.expenses TO service_role;
GRANT ALL ON public.incomes TO service_role;
GRANT ALL ON public.memories TO service_role;
GRANT ALL ON public.categories TO service_role;
GRANT ALL ON public.achievements TO service_role;
GRANT ALL ON public.ai_insights TO service_role;
GRANT ALL ON public.ai_messages TO service_role;